/***********************************************************************
* Filename: OD.c
* File description: Object Dictionary file.
* Project: EAE_Firmware
* Author: Kateryna Oliinyk
* Created Date: 03 08 2025
***********************************************************************/

/* IN REAL CANOPEN this file must be autogenerated */

/* TODO: Later these files will be included on compilation whenever we need them and
* ifs will be removed.
*/
#if CAN_OPEN

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;

#endif
