/***********************************************************************
* Filename: OD.h
* File description: Object Dictionary file.
* Project: EAE_Firmware
* Author: Kateryna Oliinyk
* Created Date: 03 08 2025
***********************************************************************/

/* IN REAL CANOPEN this file must be autogenerated */

/* TODO: Later these files will be included on compilation whenever we need them and
* ifs will be removed.
*/
#if CAN_OPEN

#ifndef _OD_H_
#define _OD_H_

/* OD structures and defines */

/* Object Dictionary */
typedef struct {
    uint16_t    size;  /**< Number of elements in the list, without last element, which is blank */
    OD_entry_t *list;  /**< List OD entries (table of contents), ordered by index */
} OD_t;

#endif
#endif
